# -*- coding: utf-8 -*-
#
## This file is part of ZENODO.
## Copyright (C) 2012, 2013, 2014 CERN.
##
## ZENODO is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## ZENODO is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with ZENODO. If not, see <http://www.gnu.org/licenses/>.
##
## In applying this licence, CERN does not waive the privileges and immunities
## granted to it by virtue of its status as an Intergovernmental Organization
## or submit itself to any jurisdiction.


language: python

services:
  - mysql
  - redis

python:
  - "2.7"

before_install:
  - "sudo add-apt-repository -y ppa:chris-lea/node.js"
  - "sudo apt-get update"

install:
  - "sudo apt-get -qy install apache2 libapache2-mod-wsgi ssl-cert poppler-utils git subversion nodejs --fix-missing"
  - "sudo a2enmod actions"
  - "sudo a2enmod version"
  - "sudo a2enmod rewrite"
  - "sudo mkdir -p /etc/apache2/ssl"
  - "sudo /usr/sbin/make-ssl-cert generate-default-snakeoil /etc/apache2/ssl/apache.pem"
  - "travis_retry pip install -r requirements.txt --exists-action i"
  - "inveniomanage config create secret-key"
  - "inveniomanage config set DEBUG False"
  - "inveniomanage config set CFG_EMAIL_BACKEND flask.ext.email.backends.console.Mail"
  - "inveniomanage config set CFG_BIBSCHED_PROCESS_USER `whoami`"
  - "inveniomanage config set CFG_TMPDIR /tmp"
  - "sudo su -c \"npm install --silent -g bower less clean-css uglify-js requirejs\""
  - "inveniomanage bower -i bower-base.json > bower.json"
  - "cat bower.json"
  - "bower install"
  - "inveniomanage config set COLLECT_STORAGE invenio.ext.collect.storage.link"
  - "inveniomanage collect > /dev/null"
  - "inveniomanage assets build"
  - "inveniomanage config set CLEANCSS_BIN false"  # deactivate all the things
  - "inveniomanage config set LESS_BIN false"      # false is /usr/bin/false
  - "inveniomanage config set REQUIREJS_BIN false"
  - "inveniomanage config set UGLIFYJS_BIN false"
  - "inveniomanage config set ASSETS_AUTO_BUILD False"

before_script:
  - "inveniomanage apache create-config"
  - "sudo ln -s $VIRTUAL_ENV/var/invenio.base-instance/apache/invenio-apache-vhost.conf /etc/apache2/sites-enabled/invenio.conf"
  - "sudo ln -s $VIRTUAL_ENV/var/invenio.base-instance/apache/invenio-apache-vhost-ssl.conf /etc/apache2/sites-enabled/invenio-ssl.conf"
  - "sudo /usr/sbin/a2dissite *default* || echo ':('"
  - "sudo /usr/sbin/a2enmod ssl" # enable SSL module
  - "sudo /usr/sbin/a2enmod xsendfile || echo ':('"
  - "sudo apachectl configtest && sudo service apache2 restart || echo 'Apache failed ...'"
  - "inveniomanage database init --yes-i-know || echo ':('"
  - "inveniomanage database create || echo ':('"
  - "inveniomanage demosite create -p zenodo.demosite"

script:
  - "python setup.py test"

notifications:
  email: false
